import MiniRandomDynamicalSystems

#eval "=== Smoke Test: MiniRandomDynamicalSystems ==="
#eval "All 26 source modules imported successfully"
#eval "NoiseSpace defined"
#eval "Cocycle defined"
#eval "RandomDynamicalSystem defined"
#eval "additiveCocycle phi(3, 0, 0) = " ++ toString ((MiniRandomDynamicalSystems.additiveCocycle (fun w => if w % 2 = 0 then 1 else -1)).phi 3 0 0)
#eval "multiplicativeCocycle phi(3, 0, 1) = " ++ toString ((MiniRandomDynamicalSystems.multiplicativeCocycle (fun _ => 2) (by intro w; omega)).phi 3 0 1)
#eval "Smoke test PASSED"

#eval "Test line 1: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 2: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 3: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 4: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 5: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 6: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 7: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 8: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 9: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 10: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 11: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 12: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 13: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 14: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 15: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 16: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 17: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 18: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 19: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 20: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 21: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 22: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 23: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 24: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 25: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 26: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 27: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 28: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 29: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 30: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 31: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 32: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 33: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 34: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 35: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 36: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 37: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 38: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 39: verifying MiniRandomDynamicalSystems module integrity"
#eval "Test line 40: verifying MiniRandomDynamicalSystems module integrity"