
import MiniRandomDynamicalSystems.Core.Basic

namespace MiniRandomDynamicalSystems

/-
# Invariants of Random Dynamical Systems -- L4

Key invariants preserved under conjugacy:
1. Lyapunov exponents (asymptotic growth rates)
2. Topological entropy (for topological RDS)
3. Invariant measures (stationary distributions)
4. Oseledets splitting (for linear cocycles)

## Lyapunov Exponent (1D)
lambda = lim_{n->oo} (1/n) log |A^n(omega)|

## Subadditive Cocycle
a_{n+m}(omega) <= a_n(omega) + a_m(theta^n omega)
Kingman's theorem: lim a_n/n exists

## Multiplicative Ergodic Theorem (Oseledets)
For linear cocycles on R^d, there exist d Lyapunov exponents
lambda_1 >= lambda_2 >= ... >= lambda_d (counting multiplicities)
and a measurable splitting (Oseledets splitting).

Knowledge: L4 Fundamental Theorems
-/

#eval "=== Properties.Invariants ==="
#eval "Lyapunov exponent: exponential growth rate"
#eval "Subadditive cocycle: Kingman theorem"
#eval "Oseledets MET: Lyapunov spectrum for linear cocycles"

-- Invariants: Line 1 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 2 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 3 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 4 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 5 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 6 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 7 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 8 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 9 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 10 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 11 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 12 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 13 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 14 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 15 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 16 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 17 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 18 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 19 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 20 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 21 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 22 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 23 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 24 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 25 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 26 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 27 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 28 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 29 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 30 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 31 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 32 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 33 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 34 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 35 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 36 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 37 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 38 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 39 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 40 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 41 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 42 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 43 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 44 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 45 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 46 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 47 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 48 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 49 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 50 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 51 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 52 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 53 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 54 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 55 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 56 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 57 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 58 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 59 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 60 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 61 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 62 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 63 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 64 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 65 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 66 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 67 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 68 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 69 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 70 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 71 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 72 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 73 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 74 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 75 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 76 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 77 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 78 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 79 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Invariants: Line 80 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.


end MiniRandomDynamicalSystems
