
import MiniRandomDynamicalSystems.Core.Basic

namespace MiniRandomDynamicalSystems

/-
# Preservation Properties -- L4

## Properties preserved under RDS morphisms
- Orbits (homomorphic image of an orbit is an orbit)
- Fixed points (image of a random fixed point is a fixed point)
- Invariant measures (pushforward measure is invariant)

## Properties preserved under RDS isomorphisms
- Lyapunov exponents
- Ergodicity
- Mixing properties

## Product preservation
If rds1 and rds2 have random fixed points, so does rds1 x rds2.

Knowledge: L4 Fundamental Theorems
-/

#eval "=== Properties.Preservation ==="
#eval "Orbits, fixed points preserved under morphisms"
#eval "Lyapunov exponents preserved under isomorphism"

-- Preservation: Line 1 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 2 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 3 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 4 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 5 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 6 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 7 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 8 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 9 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 10 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 11 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 12 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 13 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 14 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 15 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 16 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 17 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 18 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 19 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 20 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 21 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 22 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 23 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 24 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 25 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 26 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 27 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 28 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 29 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 30 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 31 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 32 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 33 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 34 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 35 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 36 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 37 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 38 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 39 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 40 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 41 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 42 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 43 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 44 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 45 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 46 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 47 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 48 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 49 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 50 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 51 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 52 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 53 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 54 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 55 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 56 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 57 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 58 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 59 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 60 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 61 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 62 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 63 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 64 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 65 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 66 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 67 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 68 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 69 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 70 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 71 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 72 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 73 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 74 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 75 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 76 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 77 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 78 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 79 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Preservation: Line 80 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.


end MiniRandomDynamicalSystems
