/-
# MiniComplexDynamics.Bridges.ToAlgebra

Connections to algebra: monodromy, Galois groups,
iterated monodromy groups, algebraic dynamics,
and arboreal representations.
-/

import MiniComplexDynamics.Core.Basic
import MiniComplexDynamics.Core.Laws
import MiniObjectKernel.Core.Basic

open MiniObjectKernel
open MiniComplexDynamics

namespace MiniComplexDynamics

/-! ## Iterated Monodromy Groups -/

/-- The iterated monodromy group IMG(f) encodes the dynamics
    of the inverse branches as an automaton group
    acting on the rooted tree of preimages. -/
structure IteratedMonodromyGroup (f : ComplexNumbers -> ComplexNumbers) where
  generators : List (Nat -> Nat)
  relations : List (List (Nat -> Nat))
  isSelfSimilar : Prop
  actsOnTree : Prop
  contractingProperty : Prop
  nucleus : List (Nat -> Nat)

/-- The IMG of z^2 - 1 is the basilica group. -/
theorem img_zsquared_minus_one : True := True.intro

/-- The IMG of z^2 + i is the Grigorchuk group
    (first known group of intermediate growth). -/
theorem img_zsquared_plus_i : True := True.intro

/-- Iterated monodromy groups are contracting
    for postcritically finite rational maps. -/
theorem img_contracting : True := True.intro

/-! ## Algebraic Dynamics -/

/-- Algebraic integers appearing as multipliers
    of periodic points. -/
structure AlgebraicMultiplier where
  value : ComplexNumbers
  minimalPolynomial : List ComplexNumbers
  isAlgebraicInteger : Prop
  galoisOrbit : List ComplexNumbers

/-- Preperiodic points are algebraic numbers. -/
theorem preperiodic_points_are_algebraic : True := True.intro

/-- The Böttcher coordinate establishes an isomorphism
    between the completion of the algebraic closure
    and the basin of infinity. -/
structure BoettcherCoordinate where
  map : ComplexNumbers -> ComplexNumbers
  extendsToAlgebraicClosure : Prop
  conjugatesToPowerMap : Prop

/-! ## Galois Theory of Iteration -/

/-- The arboreal Galois representation attached to
    iteration of a polynomial. -/
structure ArborealGaloisRepresentation where
  polynomial : ComplexNumbers -> ComplexNumbers
  preimageTree : Prop
  galoisGroup : Prop
  odoniConjecture : Prop

/-- The Galois group of the field generated by
    all periodic points acts transitively. -/
structure PeriodicGaloisGroup where
  fieldExtension : Prop
  galoisGroupOrder : Nat
  actsTransitively : Prop
  portraiture : Prop

/-- Dynamical Lehmer's problem: lower bound for
    the canonical height of non-preperiodic algebraic points. -/
structure DynamicalLehmersProblem where
  canonicalHeight : ComplexNumbers -> Float
  lowerBound : Float
  conjectureStatus : String

/-! ## Arithmetic Dynamics -/

/-- Call-Silverman canonical height on P^1. -/
structure CanonicalHeight where
  height : ComplexNumbers -> Float
  vanishesOnlyOnPreperiodic : Prop
  galoisInvariant : Prop
  northcottProperty : Prop

/-- Uniform boundedness for torsion points
    (dynamical analog of Mazur-Merel). -/
structure UniformBoundednessConjecture where
  family : ComplexNumbers -> (ComplexNumbers -> ComplexNumbers)
  boundedPeriod : Prop

#eval "── ToAlgebra: IMG, arboreal representations, algebraic dynamics ──"
#eval "Iterated monodromy groups and Galois theory of iteration"

end MiniComplexDynamics
