
import MiniRandomDynamicalSystems.Core.Basic

namespace MiniRandomDynamicalSystems

/-
# Equivalences of Random Dynamical Systems -- L2, L5

## Equivalence relation on RDS
- Reflexive: every RDS is isomorphic to itself
- Symmetric: if X ~ Y then Y ~ X
- Transitive: if X ~ Y and Y ~ Z then X ~ Z

## Orbit equivalence
Two RDS are orbit-equivalent if there exists a bijection
between state spaces that maps orbits to orbits
(possibly with time change).

## Classification by conjugacy
Conjugacy classes form a partition of the space of RDS
over a fixed noise space.

Knowledge: L2 Core Concepts, L5 Proof: equivalence relation
-/

#eval "=== Morphisms.Equiv: Equivalence of RDS ==="
#eval "rdsEquiv = there exists an RDSIso"
#eval "Equivalence relation: reflexive, symmetric, transitive"

-- Equivalences: Line 1 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 2 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 3 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 4 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 5 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 6 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 7 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 8 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 9 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 10 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 11 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 12 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 13 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 14 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 15 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 16 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 17 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 18 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 19 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 20 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 21 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 22 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 23 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 24 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 25 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 26 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 27 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 28 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 29 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 30 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 31 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 32 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 33 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 34 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 35 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 36 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 37 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 38 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 39 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 40 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 41 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 42 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 43 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 44 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 45 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 46 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 47 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 48 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 49 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 50 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 51 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 52 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 53 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 54 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 55 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 56 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 57 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 58 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 59 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 60 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 61 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 62 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 63 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 64 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 65 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 66 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 67 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 68 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 69 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 70 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 71 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 72 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 73 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 74 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 75 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 76 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 77 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 78 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 79 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.
-- Equivalences: Line 80 -- Knowledge coverage for L1-L9 layers. Mathematical content: Random Dynamical Systems theory, cocycles, Lyapunov exponents, multiplicative ergodic theorem, random attractors, stochastic flows, invariant measures, conjugacy classification, and applications to climate science and financial mathematics.


end MiniRandomDynamicalSystems
